### ISSUE TITLE
Homework3 from AlexShk

### ISSUE THREAD

**Issue by alexshk76** [WEB-road/Shkarbuta_Homework3#1]
Please verify my homework.

**Comment by Appof** [comment]
1.  Пустий тег, прибрати по всьому проекту https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/index.html#L36
2.  Навігація повинна бути посиланнями https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/index.html#L107-L113

**Comment by Appof** [comment]
3. outline краще не прибирати, він допомагає скрін рідерам орієнтуватись де знаходиться курсор https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L12-L13
4. Ці елементи і так блочні, лишній код https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L15
5. Дублюється властивість font-size https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L20-L22
6. Блокам які мають всередині контент не варто добавляти фіксовану висоту, це може зламати верстку, якщо добавити більше контенту  https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L127-L143 https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L166-L170 https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L171-L174
https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L213
7. Зробити відступи між блоками в футері можна простішим способом, цей спосіб громоздкий https://github.com/WEB-road/Shkarbuta_Homework3/blob/edf835be49fc8acb593c87097d4ac9530a867724/css/style.css#L237-L245

**Comment by Appof** [comment]
1.Контент не відцентрований, замість `margin-left` контент повинен відцентровувати container/wrapper з певними css властивостями. https://github.com/WEB-road/Shkarbuta_Homework3/blob/22584201492cfcfd77c9a97e4b742e9cd7ecf82a/css/style.css#L56-L63
Є деякі проблеми в класі wrapper: вказана ширина не відповідає тій що на макеті, флекбокси там не грають жодної ролі. 

2.  Велика вкладеність коду, тут достатньо було б одного div-елемента, тим більше, ці класи ніде не використовуються - вони пусті, а це погано створювати лишній код. https://github.com/WEB-road/Shkarbuta_Homework3/blob/22584201492cfcfd77c9a97e4b742e9cd7ecf82a/index.html#L11-L13

**Comment by alexshk76** [comment]
Please verify my homework.

**Comment by Appof** [comment]
До сих пір не виправлений головний пункт - контейнер. Де він? І чому сайт не відцентрований.
Тут забагато лишніх дів елемнтів,а також назви класів які не зустрічаються в css файлі. Треба прибрати лишнє
https://github.com/WEB-road/Shkarbuta_Homework3/blob/91a48cd6821e6285c51620f97fc20980da089b55/index.html#L70-L111
